// Re-trace the Plantim logo into ../src/plantim-geometry.mjs.
//
//   node design-tokens/icons/brand/tools/trace-plantim.mjs
//
// Needs python3 with Pillow and potrace (`brew install potrace`). This is an
// authoring tool, not part of the build: its output is committed and reviewed
// like any other hand-authored geometry, and the generator never runs it.
// See rasterize.py for how each optical grade is derived from plantim-logo.png.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { absolutePath, serializePath } from "../../../bin/lib/brand-dsl.mjs";

const here = import.meta.dirname;
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "plantim-trace-"));
// potrace: turd size, corner threshold, curve optimization tolerance
const POTRACE = {
  micro: ["-t", "60", "-a", "1.15", "-O", "0.6"],
  base: ["-t", "60", "-a", "1.15", "-O", "0.6"],
  display: ["-t", "20", "-a", "1.1", "-O", "0.8"],
};
const RASTER = 1280;

function trace(grade) {
  const pbm = path.join(tmp, `${grade}.pbm`);
  const svg = path.join(tmp, `${grade}.svg`);
  execFileSync("python3", [path.join(here, "rasterize.py"), grade, pbm], { stdio: "inherit" });
  execFileSync("potrace", [pbm, "-s", "--flat", "-o", svg, ...POTRACE[grade]], { stdio: "inherit" });
  const src = fs.readFileSync(svg, "utf8");
  // potrace writes y-up coordinates at 10x inside translate(0,H) scale(.1,-.1)
  const segs = [...src.matchAll(/ d="([^"]+)"/g)].flatMap((m) => absolutePath(m[1]));
  const px = segs.map(([c, ...n]) => {
    if (c === "Z") return ["Z"];
    const out = [c];
    for (let k = 0; k < n.length; k += 2) out.push(n[k] / 10, RASTER - n[k + 1] / 10);
    return out;
  });
  return px;
}

const grades = Object.fromEntries(["micro", "base", "display"].map((g) => [g, trace(g)]));

// One shared fit for every grade (from the display trace), so the silhouette
// never shifts between sizes: height 20 on the 24-grid, centred horizontally.
const pts = grades.display.flatMap(([c, ...n]) => n.filter((_, i) => i % 2 === 0).map((x, i) => [x, n[i * 2 + 1]]));
const xs = pts.map((p) => p[0]);
const ys = pts.map((p) => p[1]);
const [x0, x1, y0, y1] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)];
const s = 20 / (y1 - y0);
const tx = 12 - ((x0 + x1) / 2) * s;
const ty = 2 - y0 * s;

const body = Object.entries(grades)
  .map(([g, segs]) => `export const PLANTIM_${g.toUpperCase()} =\n  ${JSON.stringify(serializePath(segs, s, tx, ty))};`)
  .join("\n\n");

fs.writeFileSync(
  path.join(here, "../src/plantim-geometry.mjs"),
  `// GENERATED by tools/trace-plantim.mjs from tools/plantim-logo.png — do not edit by hand.
// Re-run the tool after changing tools/plantim-grades.json, then review the sheets.
// Filled with the even-odd rule; 24-grid, logo fitted to y 2..22.

${body}
`,
);
fs.rmSync(tmp, { recursive: true, force: true });
console.log("Wrote src/plantim-geometry.mjs");
